
from unittest.mock import Mock

import yahoo 

def test_get_current_points():
    """Ensure get_current_points returns correct answer
    """
    m_lg = Mock()

    m_lg.matchups.return_value = {'fantasy_content': {'xml:lang': 'en-US',
  'yahoo:uri': '/fantasy/v2/league/380.l.765649/scoreboard',
  'league': [{'league_key': '380.l.765649',
    'league_id': '765649',
    'name': 'The Great Allentown Fair',
    'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649',
    'logo_url': False,
    'draft_status': 'postdraft',
    'num_teams': 10,
    'edit_key': '16',
    'weekly_deadline': '',
    'league_update_timestamp': '1546500172',
    'scoring_type': 'head',
    'league_type': 'private',
    'renew': '371_525685',
    'renewed': '390_478299',
    'iris_group_chat_id': 'FWFANUFWUFAPDI4OJX6IFGFU6E',
    'allow_add_to_dl_extra_pos': 1,
    'is_pro_league': '0',
    'is_cash_league': '0',
    'current_week': '16',
    'start_week': '1',
    'start_date': '2018-09-06',
    'end_week': '16',
    'end_date': '2018-12-24',
    'is_finished': 1,
    'game_code': 'nfl',
    'season': '2018'},
   {'scoreboard': {'week': '16',
     '0': {'matchups': {'0': {'matchup': {'week': '16',
         'week_start': '2018-12-18',
         'week_end': '2018-12-24',
         'status': 'postevent',
         'is_playoffs': '1',
         'is_consolation': '1',
         'is_matchup_recap_available': 1,
         'matchup_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/recap?week=16&mid1=1&mid2=3',
         'matchup_recap_title': '...brown do for you defeat Yolo swag 420 dab in 100.12-98.30 battle',
         'matchup_grades': [{'matchup_grade': {'team_key': '380.l.765649.t.1',
            'grade': 'D'}},
          {'matchup_grade': {'team_key': '380.l.765649.t.3', 'grade': 'D'}}],
         'is_tied': 0,
         'winner_team_key': '380.l.765649.t.1',
         '0': {'teams': {'0': {'team': [[{'team_key': '380.l.765649.t.1'},
              {'team_id': '1'},
              {'name': '...brown do for you'},
              [],
              {'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/1'},
              {'team_logos': [{'team_logo': {'size': 'large',
                  'url': 'https://s.yimg.com/cv/apiv2/default/nfl/nfl_8.png'}}]},
              [],
              {'waiver_priority': 6},
              {'faab_balance': '0'},
              {'number_of_moves': '38'},
              {'number_of_trades': '2'},
              {'roster_adds': {'coverage_type': 'week',
                'coverage_value': '17',
                'value': '0'}},
              [],
              {'league_scoring_type': 'head'},
              [],
              {'draft_position': 4},
              {'has_draft_grade': 1,
               'draft_grade': 'C',
               'draft_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/1/draftrecap'},
              [],
              [],
              {'managers': [{'manager': {'manager_id': '1',
                  'nickname': 'Ravi',
                  'guid': 'O5MM6DOUQSXU24WYVTYKRTVKJQ',
                  'is_commissioner': '1',
                  'email': 'rcs131@gmail.com',
                  'image_url': 'https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg'}}]}],
             {'win_probability': 1,
              'team_points': {'coverage_type': 'week',
               'week': '16',
               'total': '100.12'},
              'team_projected_points': {'coverage_type': 'week',
               'week': '16',
               'total': '78.08'}}]},
           '1': {'team': [[{'team_key': '380.l.765649.t.3'},
              {'team_id': '3'},
              {'name': 'Yolo swag 420 dab'},
              [],
              {'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/3'},
              {'team_logos': [{'team_logo': {'size': 'large',
                  'url': 'https://s.yimg.com/cv/apiv2/default/nfl/nfl_5.png'}}]},
              [],
              {'waiver_priority': 4},
              {'faab_balance': '100'},
              {'number_of_moves': '10'},
              {'number_of_trades': 0},
              {'roster_adds': {'coverage_type': 'week',
                'coverage_value': '17',
                'value': '0'}},
              [],
              {'league_scoring_type': 'head'},
              [],
              {'draft_position': 8},
              {'has_draft_grade': 1,
               'draft_grade': 'B-',
               'draft_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/3/draftrecap'},
              [],
              [],
              {'managers': [{'manager': {'manager_id': '3',
                  'nickname': 'gregorypost89',
                  'guid': '6DJJL5QQBWTBUDKVG6POXF2X2A',
                  'email': 'gregorypost89@gmail.com',
                  'image_url': 'https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg'}}]}],
             {'win_probability': 0,
              'team_points': {'coverage_type': 'week',
               'week': '16',
               'total': '98.30'},
              'team_projected_points': {'coverage_type': 'week',
               'week': '16',
               'total': '93.74'}}]},
           'count': 2}}}},
       '1': {'matchup': {'week': '16',
         'week_start': '2018-12-18',
         'week_end': '2018-12-24',
         'status': 'postevent',
         'is_playoffs': '1',
         'is_consolation': '0',
         'is_matchup_recap_available': 1,
         'matchup_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/recap?week=16&mid1=4&mid2=10',
         'matchup_recap_title': 'Easy Drake oven beat The Gurley Show for fourth straight win in 144.66-118.34 rout',
         'matchup_grades': [{'matchup_grade': {'team_key': '380.l.765649.t.4',
            'grade': 'B-'}},
          {'matchup_grade': {'team_key': '380.l.765649.t.10', 'grade': 'B'}}],
         'is_tied': 0,
         'winner_team_key': '380.l.765649.t.10',
         '0': {'teams': {'0': {'team': [[{'team_key': '380.l.765649.t.4'},
              {'team_id': '4'},
              {'name': 'The Gurley Show'},
              [],
              {'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/4'},
              {'team_logos': [{'team_logo': {'size': 'large',
                  'url': 'https://s.yimg.com/cv/apiv2/default/nfl/nfl_11.png'}}]},
              [],
              {'waiver_priority': 7},
              {'faab_balance': '0'},
              {'number_of_moves': '40'},
              {'number_of_trades': '1'},
              {'roster_adds': {'coverage_type': 'week',
                'coverage_value': '17',
                'value': '0'}},
              {'clinched_playoffs': 1},
              {'league_scoring_type': 'head'},
              [],
              {'draft_position': 2},
              {'has_draft_grade': 1,
               'draft_grade': 'C',
               'draft_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/4/draftrecap'},
              [],
              [],
              {'managers': [{'manager': {'manager_id': '4',
                  'nickname': 'Rahul',
                  'guid': 'YJYCWKNRY2GD3AZS2HEXGDQ5PE',
                  'email': 'rkale17@gmail.com',
                  'image_url': 'https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg'}}]}],
             {'win_probability': 0,
              'team_points': {'coverage_type': 'week',
               'week': '16',
               'total': '118.34'},
              'team_projected_points': {'coverage_type': 'week',
               'week': '16',
               'total': '131.16'}}]},
           '1': {'team': [[{'team_key': '380.l.765649.t.10'},
              {'team_id': '10'},
              {'name': 'Easy Drake oven'},
              [],
              {'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/10'},
              {'team_logos': [{'team_logo': {'size': 'large',
                  'url': 'https://s.yimg.com/cv/apiv2/default/nfl/nfl_4.png'}}]},
              [],
              {'waiver_priority': 9},
              {'faab_balance': '22'},
              {'number_of_moves': '37'},
              {'number_of_trades': 0},
              {'roster_adds': {'coverage_type': 'week',
                'coverage_value': '17',
                'value': '0'}},
              {'clinched_playoffs': 1},
              {'league_scoring_type': 'head'},
              [],
              {'draft_position': 5},
              {'has_draft_grade': 1,
               'draft_grade': 'B',
               'draft_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/10/draftrecap'},
              [],
              [],
              {'managers': [{'manager': {'manager_id': '10',
                  'nickname': 'Pinang',
                  'guid': '4MCLU6BYC56YBMK2MCVWWPCBOM',
                  'email': 'pinang@gmail.com',
                  'image_url': 'https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg'}}]}],
             {'win_probability': 1,
              'team_points': {'coverage_type': 'week',
               'week': '16',
               'total': '144.66'},
              'team_projected_points': {'coverage_type': 'week',
               'week': '16',
               'total': '142.67'}}]},
           'count': 2}}}},
       '2': {'matchup': {'week': '16',
         'week_start': '2018-12-18',
         'week_end': '2018-12-24',
         'status': 'postevent',
         'is_playoffs': '1',
         'is_consolation': '1',
         'is_matchup_recap_available': 1,
         'matchup_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/recap?week=16&mid1=5&mid2=8',
         'matchup_recap_title': "BetterGoEatSome Soup earn win against Sy's Slam-Dunk Team in 133.28-105.52 rout",
         'matchup_grades': [{'matchup_grade': {'team_key': '380.l.765649.t.5',
            'grade': 'B'}},
          {'matchup_grade': {'team_key': '380.l.765649.t.8', 'grade': 'C'}}],
         'is_tied': 0,
         'winner_team_key': '380.l.765649.t.5',
         '0': {'teams': {'0': {'team': [[{'team_key': '380.l.765649.t.5'},
              {'team_id': '5'},
              {'name': 'BetterGoEatSome Soup'},
              {'is_owned_by_current_login': 1},
              {'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/5'},
              {'team_logos': [{'team_logo': {'size': 'large',
                  'url': 'https://s.yimg.com/cv/apiv2/default/nfl/nfl_6.png'}}]},
              [],
              {'waiver_priority': 5},
              {'faab_balance': '50'},
              {'number_of_moves': '15'},
              {'number_of_trades': 0},
              {'roster_adds': {'coverage_type': 'week',
                'coverage_value': '17',
                'value': '0'}},
              [],
              {'league_scoring_type': 'head'},
              [],
              {'draft_position': 1},
              {'has_draft_grade': 1,
               'draft_grade': 'A-',
               'draft_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/5/draftrecap'},
              [],
              [],
              {'managers': [{'manager': {'manager_id': '5',
                  'nickname': 'Sahil',
                  'guid': 'WUAYDHNZ23GD3ITDXABYEMDRIA',
                  'is_current_login': '1',
                  'email': 'sahil89@gmail.com',
                  'image_url': 'https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg'}}]}],
             {'win_probability': 1,
              'team_points': {'coverage_type': 'week',
               'week': '16',
               'total': '133.28'},
              'team_projected_points': {'coverage_type': 'week',
               'week': '16',
               'total': '113.61'}}]},
           '1': {'team': [[{'team_key': '380.l.765649.t.8'},
              {'team_id': '8'},
              {'name': "Sy's Slam-Dunk Team"},
              [],
              {'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/8'},
              {'team_logos': [{'team_logo': {'size': 'large',
                  'url': 'https://s.yimg.com/cv/apiv2/default/nfl/nfl_8.png'}}]},
              [],
              {'waiver_priority': 3},
              {'faab_balance': '88'},
              {'number_of_moves': '13'},
              {'number_of_trades': 0},
              {'roster_adds': {'coverage_type': 'week',
                'coverage_value': '17',
                'value': '0'}},
              [],
              {'league_scoring_type': 'head'},
              [],
              {'draft_position': 9},
              {'has_draft_grade': 1,
               'draft_grade': 'B+',
               'draft_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/8/draftrecap'},
              [],
              [],
              {'managers': [{'manager': {'manager_id': '8',
                  'nickname': 'Sy',
                  'guid': 'S5DS4A3ZVERR5QZ7VBCHZVTCAU',
                  'email': 'aisixers2000@yahoo.com',
                  'image_url': 'https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg'}}]}],
             {'win_probability': 0,
              'team_points': {'coverage_type': 'week',
               'week': '16',
               'total': '105.52'},
              'team_projected_points': {'coverage_type': 'week',
               'week': '16',
               'total': '113.75'}}]},
           'count': 2}}}},
       '3': {'matchup': {'week': '16',
         'week_start': '2018-12-18',
         'week_end': '2018-12-24',
         'status': 'postevent',
         'is_playoffs': '1',
         'is_consolation': '0',
         'is_matchup_recap_available': 1,
         'matchup_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/recap?week=16&mid1=6&mid2=7',
         'matchup_recap_title': 'Despite top scorer Ertz, Shady fall to Comeback Train in 141.02-118.84 rout',
         'matchup_grades': [{'matchup_grade': {'team_key': '380.l.765649.t.6',
            'grade': 'C'}},
          {'matchup_grade': {'team_key': '380.l.765649.t.7', 'grade': 'B+'}}],
         'is_tied': 0,
         'winner_team_key': '380.l.765649.t.7',
         '0': {'teams': {'0': {'team': [[{'team_key': '380.l.765649.t.6'},
              {'team_id': '6'},
              {'name': 'Shady'},
              [],
              {'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/6'},
              {'team_logos': [{'team_logo': {'size': 'large',
                  'url': 'https://s.yimg.com/cv/apiv2/default/nfl/nfl_4.png'}}]},
              [],
              {'waiver_priority': 10},
              {'faab_balance': '100'},
              {'number_of_moves': '3'},
              {'number_of_trades': 0},
              {'roster_adds': {'coverage_type': 'week',
                'coverage_value': '17',
                'value': '0'}},
              {'clinched_playoffs': 1},
              {'league_scoring_type': 'head'},
              [],
              {'draft_position': 6},
              {'has_draft_grade': 1,
               'draft_grade': 'B',
               'draft_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/6/draftrecap'},
              [],
              [],
              {'managers': [{'manager': {'manager_id': '6',
                  'nickname': 'AirM',
                  'guid': 'WEFJYDUXRRSUQKQOSD2BI52XKY',
                  'email': 'air_jordan_2_da_max@yahoo.com',
                  'image_url': 'https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg'}}]}],
             {'win_probability': 0,
              'team_points': {'coverage_type': 'week',
               'week': '16',
               'total': '118.84'},
              'team_projected_points': {'coverage_type': 'week',
               'week': '16',
               'total': '120.52'}}]},
           '1': {'team': [[{'team_key': '380.l.765649.t.7'},
              {'team_id': '7'},
              {'name': 'Comeback Train'},
              [],
              {'url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/7'},
              {'team_logos': [{'team_logo': {'size': 'large',
                  'url': 'https://s.yimg.com/cv/apiv2/default/nfl/nfl_6.png'}}]},
              [],
              {'waiver_priority': 8},
              {'faab_balance': '0'},
              {'number_of_moves': '40'},
              {'number_of_trades': 0},
              {'roster_adds': {'coverage_type': 'week',
                'coverage_value': '17',
                'value': '0'}},
              {'clinched_playoffs': 1},
              {'league_scoring_type': 'head'},
              [],
              {'draft_position': 10},
              {'has_draft_grade': 1,
               'draft_grade': 'C',
               'draft_recap_url': 'https://football.fantasysports.yahoo.com/2018/f1/765649/7/draftrecap'},
              [],
              [],
              {'managers': [{'manager': {'manager_id': '7',
                  'nickname': 'Alex',
                  'guid': '5EHRIF7WIT5A62VA6XKU3HDELY',
                  'email': 'alexrrosen1@gmail.com',
                  'image_url': 'https://s.yimg.com/ag/images/default_user_profile_pic_64sq.jpg'}}]}],
             {'win_probability': 1,
              'team_points': {'coverage_type': 'week',
               'week': '16',
               'total': '141.02'},
              'team_projected_points': {'coverage_type': 'week',
               'week': '16',
               'total': '137.14'}}]},
           'count': 2}}}},
       'count': 4}}}}],
  'time': '282.85503387451ms',
  'copyright': 'Data provided by Yahoo! and STATS, LLC',
  'refresh_rate': '60'}}


    actual = yahoo.get_current_points(m_lg)

    expected = {'380.l.765649.t.1': '100.12',
                '380.l.765649.t.3': '98.30',
                '380.l.765649.t.4': '118.34',
                '380.l.765649.t.10': '144.66',
                '380.l.765649.t.5': '133.28',
                '380.l.765649.t.8': '105.52',
                '380.l.765649.t.6': '118.84',
                '380.l.765649.t.7': '141.02'}

    assert expected == actual






